# Generated by Django 4.1.3 on 2022-11-28 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Complainant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("id_number", models.CharField(max_length=8, null=True)),
                ("phone", models.CharField(max_length=255, null=True)),
                ("age", models.PositiveSmallIntegerField()),
                ("address", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurrence_book_number", models.CharField(max_length=13)),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                ("statement", models.TextField()),
                ("location", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Solved", "Solved"),
                            ("Cold", "Cold"),
                        ],
                        default="Active",
                        max_length=255,
                    ),
                ),
                (
                    "complainant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="precinct.complainant",
                    ),
                ),
            ],
            options={
                "ordering": ["occurrence_book_number"],
            },
        ),
        migrations.CreateModel(
            name="LastSeen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Officer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("badge", models.CharField(max_length=8)),
                ("id_number", models.CharField(max_length=8)),
                ("phone", models.CharField(max_length=255)),
                ("birth_date", models.DateField()),
                (
                    "general_duty",
                    models.CharField(
                        choices=[
                            (
                                "Officer Commanding Station",
                                "Officer Commanding Station",
                            ),
                            ("Officer", "Officer"),
                            ("Detective", "Detective"),
                        ],
                        default="Officer",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="Suspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("id_number", models.CharField(max_length=8, null=True)),
                ("phone", models.CharField(max_length=255, null=True)),
                ("age", models.PositiveSmallIntegerField()),
                ("address", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                (
                    "officer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="precinct.officer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lawyer",
            fields=[
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("id_number", models.CharField(max_length=8)),
                ("phone", models.CharField(max_length=255)),
                (
                    "suspect",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="precinct.suspect",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="precinct.officer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MostWanted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("id_number", models.CharField(max_length=8, null=True)),
                ("age", models.PositiveSmallIntegerField()),
                ("bounty", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="precinct.complaint",
                    ),
                ),
                ("last_seen", models.ManyToManyField(to="precinct.lastseen")),
            ],
        ),
        migrations.CreateModel(
            name="MissingPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("id_number", models.CharField(max_length=8, null=True)),
                ("age", models.PositiveSmallIntegerField()),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="precinct.complaint",
                    ),
                ),
                ("last_seen", models.ManyToManyField(to="precinct.lastseen")),
            ],
        ),
        migrations.CreateModel(
            name="Detective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report", models.TextField()),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="precinct.complaint",
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="precinct.officer",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DayOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="precinct.officer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="complaint",
            name="recording_officer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="precinct.officer",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="suspects",
            field=models.ManyToManyField(to="precinct.suspect"),
        ),
        migrations.CreateModel(
            name="BountyHunter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("id_number", models.CharField(max_length=8, null=True)),
                ("phone", models.CharField(max_length=255, null=True)),
                ("age", models.PositiveSmallIntegerField()),
                ("address", models.CharField(max_length=255)),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "most_wanted",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="precinct.mostwanted",
                    ),
                ),
            ],
        ),
    ]
